networks:
  snake-net:
    name: snake-net
    driver: bridge

include:
  - path: service/api-gateway/docker-compose.yml
  - path: service/encyclopedia/docker-compose.yml
  - path: service/ai/docker-compose.yaml
  - path: service/frontend/docker-compose.yml
  - path: database/image_storage/docker-compose.yml
  - path: database/log_storage/docker-compose.yml
  - path: database/wiki_snake_storage/docker-compose.yml
