services:
  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - ${MONGO_PORT}

  api:
    build: ./gate-way-img
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
    ports:
      - ${API_MONGO_PORT}

volumes:
  mongo_data:
