services:
  mongo:
    image: mongo:7
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - snake-net

  image-storage:
    build: ./gate-way-img
    container_name: image-storage
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://${MONGO_ROOT_NAME}:${MONGO_ROOT_PASS}@mongo:27017/image_db?authSource=admin
    depends_on:
      - mongo
    ports:
      - "5002:5002"
    volumes:
      - image_uploads:/app/uploads
    networks:
      - snake-net

networks:
  snake-net:
    name: snake-net

volumes:
  mongo_data:
  image_uploads:
