services:
  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - ${MONGO_PORT}

  api:
    build: ./gate-way-img
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://${MONGO_ROOT_NAME}:${MONGO_ROOT_PASS}@mongo:27017/image_db?authSource=admin
    depends_on:
      - mongo
    ports:
      - "5002:5002"

volumes:
  mongo_data:
